all:
  hosts:
    master-0:
      ansible_host: 158.160.85.254
    worker-0:
      ansible_host: 158.160.0.194
    worker-1:
      ansible_host: 51.250.41.57
  vars:
    ansible_user: kunaev
    ansible_ssh_private_key_file: "~/.ssh/settings"
    ansible_become_method: sudo
masters:
  hosts:
    master-0:
workers:
  hosts:
    worker-0:
    worker-1:
