---
- name: Install control plane
  hosts: all
  become: true
  tasks:
    - name: Masters settings
      block:
        - name: Init master
          shell: kubeadm init --pod-network-cidr=10.244.0.0/16
          ignore_errors: true

        - name: Set KUBECONFIG env
          lineinfile:
            path: /etc/environment
            line: export KUBECONFIG=/etc/kubernetes/admin.conf

        - name: Get join command
          shell: kubeadm token create --print-join-command
          register: join_command_raw
            
        - name: Install CNI
          shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      when: "'masters' in group_names"

    - name: Workers Settings
      block:
        - name: Init workers
          shell: "{{ hostvars[groups['masters'].0].join_command_raw.stdout }}"
          ignore_errors: true
      when: "'workers' in group_names"
