all:
  hosts:
    master-0:
      ansbile_host: 158.160.42.190
      ip: 192.168.20.4
    master-1:
      ansbile_host: 158.160.82.162
      ip: 192.168.21.4
    master-2:
      ansbile_host: 51.250.35.54
      ip: 192.168.22.11
    worker-0:
      ansbile_host: 
      ip: 192.168.21.30
    worker-1:  
      ansbile_host: 
      ip: 192.168.22.27
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/settings"
    ansible_become_method: sudo
  children:
    kube_control_plane:
      hosts:
        master-0:
        master-1:
        master-2:
    kube_node:
      hosts:
        worker-0:
        worker-1:
    etcd:
      hosts:
        master-0:
        master-1:
        master-2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
